FROM dijksterhuis/cleverspeech:build

USER cleverspeech
RUN cd ${CLEVERSPEECH_HOME} \
 && git checkout master \
 && git pull --recurse-submodules \
 && echo "Completed checkouts."
RUN python3 -m pip install -e ${CLEVERSPEECH_HOME}
USER root