FROM dijksterhuis/cleverspeech:latest

USER cleverspeech
ARG branch=master
RUN cd ${CLEVERSPEECH_HOME} \
 && git checkout ${branch} \
 && git pull --recurse-submodules \
 && echo "Completed checkouts."
RUN python3 -m pip install --user -e ${CLEVERSPEECH_HOME}
USER root